create table answers (answer_id bigint not null auto_increment, content_id bigint, question_id bigint, primary key (answer_id)) engine=InnoDB;
create table content (content_id bigint not null auto_increment, created_at datetime(6), description varchar(255), picture LONGTEXT, updated_at datetime(6), user_id bigint, primary key (content_id)) engine=InnoDB;
create table questions (question_id bigint not null auto_increment, title varchar(255), content_id bigint, primary key (question_id)) engine=InnoDB;
create table questions_tags (question_id bigint not null, tag_id bigint not null, primary key (question_id, tag_id)) engine=InnoDB;
create table tags (tag_id bigint not null auto_increment, name varchar(255), primary key (tag_id)) engine=InnoDB;
create table users (user_id bigint not null auto_increment, e_mail varchar(255), f_name varchar(255), l_name varchar(255), password varchar(255), role varchar(255), primary key (user_id)) engine=InnoDB;
create table votes (type varchar(255), value integer, user_user_id bigint not null, content_content_id bigint not null, primary key (content_content_id, user_user_id)) engine=InnoDB;
alter table users add constraint UK_ehv2osdo3bfokh566calsfx32 unique (e_mail);
alter table answers add constraint FKqolg9rmukcj8w7j2j6f0os2wr foreign key (content_id) references content (content_id) on delete cascade;
alter table answers add constraint FK3erw1a3t0r78st8ty27x6v3g1 foreign key (question_id) references questions (question_id);
alter table content add constraint FK8ha3wmua0lw7fp1km9t8deutx foreign key (user_id) references users (user_id);
alter table questions add constraint FK8aq2mp5u9col4b9wm5m9kc5un foreign key (content_id) references content (content_id) on delete cascade;
alter table questions_tags add constraint FK7yq8xf1pqv8katljm8v8j8w3c foreign key (tag_id) references tags (tag_id);
alter table questions_tags add constraint FK4u5xv906wfevngoe973bec6u0 foreign key (question_id) references questions (question_id);
alter table votes add constraint FKlxm89umrp9p95hduquwivsl4r foreign key (content_content_id) references content (content_id);
alter table votes add constraint FK2bgdlmtft49agw7mnhftfs7lt foreign key (user_user_id) references users (user_id);
